### ISSUE TITLE
Add AUTHORS

### ISSUE THREAD

**Issue by RabeaMue** [foerstner-lab/Bits_and_pieces_for_the_carpentries_workshops#25]
Hi @konrad @Tillsa @VScharf7 @LukasCBossert 

please confirm that you wish to be added to the list of contributors for this repository. 
The content is licensed under the CC BY licence

**Comment by LukasCBossert** [comment]
Hi @RabeaMue , I am fine being added as contributor.

**Comment by silviadg87** [comment]
Hi @RabeaMue I am also fine

**Comment by VScharf7** [comment]
Hi @RabeaMue. also fine with me. Thank you
